include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_interpolation_to_compose_strings: false
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
