import 'package:recipes/app/utils/constants/sizer.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:get/get.dart';

ThemeData lightTheme = ThemeData(
  colorScheme: const ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF765B00),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFFFDF92),
    onPrimaryContainer: Color(0xFF241A00),
    secondary: Color(0xFF6A5D3F),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFF3E1BB),
    onSecondaryContainer: Color(0xFF231A04),
    tertiary: Color(0xFF486549),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFC9EBC7),
    onTertiaryContainer: Color(0xFF05210B),
    error: Color(0xFFBA1A1A),
    errorContainer: Color(0xFFFFDAD6),
    onError: Color(0xFFFFFFFF),
    onErrorContainer: Color(0xFF410002),
    background: Color(0xFFFFFBFF),
    onBackground: Color(0xFF1E1B16),
    surface: Color(0xFFFFFBFF),
    onSurface: Color(0xFF1E1B16),
    surfaceVariant: Color(0xFFECE1CF),
    onSurfaceVariant: Color(0xFF4C4639),
    outline: Color(0xFF7E7667),
    onInverseSurface: Color(0xFFF7F0E7),
    inverseSurface: Color(0xFF33302A),
    inversePrimary: Color(0xFFF4BF00),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFF765B00),
    outlineVariant: Color(0xFFCFC5B4),
    scrim: Color(0xFF000000),
  ),
  chipTheme: ChipThemeData(
    backgroundColor: const Color(0xFFf7f7f7),
    padding: EdgeInsets.symmetric(vertical: kHeight5, horizontal: kWidth5),
    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(Get.width)),
    side: BorderSide.none,
  ),
  bottomAppBarTheme: const BottomAppBarTheme(color: Color(0xffffffff)),
  disabledColor: const Color(0xff848484),
  splashColor: Colors.transparent,
  highlightColor: Colors.transparent,
  iconTheme: IconThemeData(
    color: const Color(0xff515151),
    size: kFontSize24,
  ),
  scaffoldBackgroundColor: const Color(0xFFf7f7f7),
  appBarTheme: AppBarTheme(
    toolbarHeight: kHeight56,
    actionsIconTheme: IconThemeData(
      color: Colors.black,
      size: kHeight24,
    ),
    iconTheme: IconThemeData(
      color: Colors.black,
      size: kHeight24,
    ),
    backgroundColor: const Color(0xffffffff),
    titleTextStyle: TextStyle(
      color: const Color(0xff000000),
      fontWeight: FontWeight.w500,
      fontSize: kFontSize20,
    ),
    systemOverlayStyle: const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarBrightness: Brightness.light,
      statusBarIconBrightness: Brightness.dark,
      systemNavigationBarColor: Color(0xffffffff),
      systemNavigationBarIconBrightness: Brightness.dark,
    ),
    surfaceTintColor: Colors.white,
    elevation: 0,
    centerTitle: true,
  ),
  cardTheme: const CardTheme(
    color: Colors.white,
    surfaceTintColor: Colors.white,
  ),
  dividerColor: Colors.grey.shade500,
  visualDensity: VisualDensity.adaptivePlatformDensity,
  useMaterial3: true,
);
